apiVersion: v2
name: dev-stack
version: 0.1.0
dependencies:
  - name: postgres
    version: 0.12.3
    repository: "oci://registry-1.docker.io/cloudpirates"
    alias: dev-postgres
  - name: rabbitmq
    version: 0.7.9
    repository: "oci://registry-1.docker.io/cloudpirates"
    alias: dev-rabbitmq
  - name: keycloak
    version: 0.11.0
    repository: "oci://registry-1.docker.io/cloudpirates"
    alias: dev-keycloak
  - name: ort-server
    version: 0.1.0
    repository: "file://../ort-server"
